drop sequence myseq;
create sequence myseq increment by 1 start with 1;
insert into mydept values(myseq.nextval,'系统软件部');
select * from mydept;
alter sequence myseq increment by 2;
drop table mydept;
create table mydept(deptno number generated by default as identity ( start with 1 increment by 1),dname varchar2(20)); 
drop table mydept;
create table mydept(deptnum number,dname varchar2(20)); 
create sequence deptnum_seq increment by 1 start with 1;
select * from mydept;
insert into mydept (dname) values ('系统软件部');
drop trigger mydept_trigger;
create or replace trigger mydept_trigger 
before
insert on mydept
for each row
begin
select deptnum_seq.nextval into :New.deptnum from dual;
end;

